server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.htm;
    charset utf-8;

    gzip on;
    gzip_static on;
    gzip_buffers 4 16k;
    gzip_comp_level 2;
    gzip_vary off;
    gzip_min_length 100;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml application/json;
    gzip_disable "MSIE [1-6]\\.";

    location ~* \.(js|css|html|svg|json|ttf|woff|woff2)$ {
        gzip_static on;
        expires 5d;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri /index.html;
    }

    location = /index.html {
        internal;
        add_header Cache-Control 'no-store';
    }

    location /health {
        add_header Content-Type text/plain;
        return 200 "OK";
    }

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nAllow: /\n";
    }
}
